import { findOrCreateTab, connect } from './cdp.mjs';
const tab = await findOrCreateTab('http://gdemos.ddns.net/cypdemo/');
console.log('URL:', tab.url);
const cdp = await connect(tab.webSocketDebuggerUrl);
await cdp.send('Runtime.enable');
const ev = await cdp.send('Runtime.evaluate', { expression: `(() => {
  const out = {};
  out.texto = (document.body.innerText||'').slice(0,1800);
  const items = [...document.querySelectorAll('.x-menu-item-text, .x-menu-list-item, td.x-btn-mc, .x-btn-inner, .x-btn-text')];
  out.items = items.map(e => ({ txt: (e.innerText||e.textContent||'').trim(), cls: e.className, id: e.id || '' })).filter(x => x.txt.length>0 && x.txt.length<40);
  out.submenus = [...document.querySelectorAll('.x-menu')].map(m=>({vis: getComputedStyle(m).display, items:[...m.querySelectorAll('.x-menu-item-text')].map(i=>i.innerText.trim()).filter(Boolean)}));
  out.tabs = [...document.querySelectorAll('.x-tab-strip-text, .x-tab-inner')].map(e=>e.innerText.trim()).filter(Boolean);
  out.windows = [...document.querySelectorAll('.x-window')].map(w=>({vis:getComputedStyle(w).display, title:(w.querySelector('.x-window-header-text')?.innerText||'').trim()}));
  out.grids = [...document.querySelectorAll('.x-grid3')].map(g=>({cols:[...g.querySelectorAll('.x-grid3-hd-inner')].map(h=>h.innerText.trim()).filter(Boolean), rows:g.querySelectorAll('.x-grid3-row').length}));
  out.forms = [...document.querySelectorAll('.x-form-field')].map(f=>({id:f.id, name:f.name||'', tipo:f.type||f.tagName, lbl:(f.closest('.x-form-item')?.querySelector('label')?.innerText||'').trim()}));
  return out;
})()`, returnByValue: true });
const v = ev.result?.result?.value;
console.log('=== TEXTO ==='); console.log(v.texto);
console.log('=== ITEMS MENU ==='); console.log(JSON.stringify(v.items));
console.log('=== SUBMENUS ==='); console.log(JSON.stringify(v.submenus));
console.log('=== TABS ==='); console.log(JSON.stringify(v.tabs));
console.log('=== WINDOWS ==='); console.log(JSON.stringify(v.windows));
console.log('=== GRIDS ==='); console.log(JSON.stringify(v.grids));
console.log('=== FORMS ==='); console.log(JSON.stringify(v.forms));
cdp.close();