import { findOrCreateTab, connect } from './cdp.mjs';
const tab = await findOrCreateTab('http://gdemos.ddns.net/cypdemo/');
const cdp = await connect(tab.webSocketDebuggerUrl);
await cdp.send('Runtime.enable');
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const run = async (expr) => (await cdp.send('Runtime.evaluate', { expression: expr, returnByValue: true })).result?.result?.value;
const clickAt = async (x,y) => {
  await cdp.send('Input.dispatchMouseEvent', { type:'mouseMoved', x, y });
  await sleep(200);
  await cdp.send('Input.dispatchMouseEvent', { type:'mousePressed', x, y, button:'left', clickCount:1 });
  await cdp.send('Input.dispatchMouseEvent', { type:'mouseReleased', x, y, button:'left', clickCount:1 });
};
const v0 = await run(`(() => [...document.querySelectorAll('.x-window')].filter(w=>getComputedStyle(w).display!=='none' && (w.querySelector('.x-window-header-text')?.innerText||'').trim()).map(w=>({title:(w.querySelector('.x-window-header-text')?.innerText||'').trim(), z:parseInt(w.style.zIndex||'0',10)})))()`);
console.log('ANTES:', JSON.stringify(v0));
const L = await run(`(() => { const el=document.getElementById('O174_id'); if(!el) return null; const r=el.getBoundingClientRect(); return {x:r.x+r.width/2, y:r.y+r.height/2, w:r.width, h:r.height, vis:getComputedStyle(el).display, txt:(el.innerText||'').trim()}; })()`);
console.log('LOC Cargos:', JSON.stringify(L));
await clickAt(L.x, L.y);
await sleep(3500);
const v1 = await run(`(() => [...document.querySelectorAll('.x-window')].filter(w=>getComputedStyle(w).display!=='none' && (w.querySelector('.x-window-header-text')?.innerText||'').trim()).map(w=>({title:(w.querySelector('.x-window-header-text')?.innerText||'').trim(), z:parseInt(w.style.zIndex||'0',10)})))()`);
console.log('DESPUES:', JSON.stringify(v1));
cdp.close();