ALTER TABLE charges ADD COLUMN IF NOT EXISTS concept text NOT NULL DEFAULT '';
ALTER TABLE charges ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'Peso Dominicano';
ALTER TABLE charges ADD COLUMN IF NOT EXISTS note text NOT NULL DEFAULT '';
