BEGIN;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS number text NOT NULL DEFAULT '';
ALTER TABLE zones ADD COLUMN IF NOT EXISTS range_from text NOT NULL DEFAULT '';
ALTER TABLE zones ADD COLUMN IF NOT EXISTS range_to text NOT NULL DEFAULT '';
ALTER TABLE zones ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS number text NOT NULL DEFAULT '';
ALTER TABLE routes ADD COLUMN IF NOT EXISTS range_from text NOT NULL DEFAULT '';
ALTER TABLE routes ADD COLUMN IF NOT EXISTS range_to text NOT NULL DEFAULT '';
ALTER TABLE routes ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE collectors ALTER COLUMN lat DROP NOT NULL;
ALTER TABLE collectors ALTER COLUMN lng DROP NOT NULL;
ALTER TABLE collectors ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
ALTER TABLE collectors ADD COLUMN IF NOT EXISTS ident text NOT NULL DEFAULT '';
ALTER TABLE collectors ADD COLUMN IF NOT EXISTS cellular text NOT NULL DEFAULT '';
ALTER TABLE collectors ADD COLUMN IF NOT EXISTS account_code text NOT NULL DEFAULT '';
ALTER TABLE services ADD COLUMN IF NOT EXISTS abbreviation text NOT NULL DEFAULT '';
ALTER TABLE services ADD COLUMN IF NOT EXISTS caption text NOT NULL DEFAULT '';
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS client_id text REFERENCES clients(id);
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS day1 text NOT NULL DEFAULT '';
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS day2 text NOT NULL DEFAULT '';
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'Peso Dominicano';
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS concept text NOT NULL DEFAULT '';
ALTER TABLE recurring_charges ADD COLUMN IF NOT EXISTS note text NOT NULL DEFAULT '';
ALTER TABLE recurring_charges DROP CONSTRAINT IF EXISTS recurring_charges_frequency_check;
ALTER TABLE recurring_charges ADD CONSTRAINT recurring_charges_frequency_check
  CHECK (frequency IN ('undefined','daily','every_other_day','weekly','fortnightly','monthly','quarterly','four_monthly','semiannual','yearly'));
COMMIT;
