-- CyP installation keys are logical identities, independent of VALSTAT and
-- existing station licenses. No namespace is generated by this migration.
CREATE TABLE station_installation_scope (
  id text PRIMARY KEY CHECK (id = 'main'),
  scope_id uuid NOT NULL UNIQUE
);

CREATE TABLE station_installations (
  namespace_id uuid NOT NULL REFERENCES station_installation_scope(scope_id),
  scope_id text NOT NULL CHECK (char_length(scope_id) BETWEEN 1 AND 1024),
  station_id text NOT NULL REFERENCES pcp_stations(id),
  installation_id text NOT NULL CHECK (installation_id ~ '^CYP-INST-[a-f0-9]{64}$'),
  public_key_spki text NOT NULL CHECK (public_key_spki ~ '^[A-Za-z0-9_-]{122}$'),
  algorithm text NOT NULL CHECK (algorithm = 'ECDSA-P256-SHA256'),
  status text NOT NULL CHECK (status IN ('active','revoked')),
  revision uuid NOT NULL,
  registered_at timestamptz NOT NULL,
  registered_by text NOT NULL CHECK (char_length(registered_by) BETWEEN 1 AND 80 AND registered_by !~ '[[:cntrl:]]'),
  revoked_at timestamptz,
  revoked_by text CHECK (char_length(revoked_by) BETWEEN 1 AND 80 AND revoked_by !~ '[[:cntrl:]]'),
  revocation_reason text CHECK (char_length(trim(revocation_reason)) BETWEEN 1 AND 1000),
  PRIMARY KEY (scope_id,station_id,installation_id),
  CHECK (jsonb_typeof(scope_id::jsonb) = 'array' AND jsonb_array_length(scope_id::jsonb) = 2
    AND jsonb_typeof(scope_id::jsonb->0) = 'string' AND scope_id::jsonb->>0 = namespace_id::text
    AND (scope_id::jsonb->1 = 'null'::jsonb OR (jsonb_typeof(scope_id::jsonb->1) = 'string'
      AND char_length(scope_id::jsonb->>1) BETWEEN 1 AND 80))),
  CHECK ((status = 'active' AND revoked_at IS NULL AND revoked_by IS NULL AND revocation_reason IS NULL)
    OR (status = 'revoked' AND revoked_at IS NOT NULL AND revoked_by IS NOT NULL AND revocation_reason IS NOT NULL
      AND revoked_at >= registered_at))
);
CREATE INDEX station_installations_station_status ON station_installations(station_id,status);

-- Sessions already allow authenticated bootstrap actors without a provisioned
-- users row. Preserve that contract while enforcing this challenge's actor.
CREATE UNIQUE INDEX auth_sessions_id_user ON auth_sessions(id,user_id);
CREATE TABLE station_installation_challenges (
  namespace_id uuid NOT NULL REFERENCES station_installation_scope(scope_id),
  scope_id text NOT NULL CHECK (char_length(scope_id) BETWEEN 1 AND 1024),
  station_id text NOT NULL REFERENCES pcp_stations(id),
  installation_id text NOT NULL CHECK (installation_id ~ '^CYP-INST-[a-f0-9]{64}$'),
  challenge_id uuid PRIMARY KEY,
  version text NOT NULL CHECK (version = 'CYP-INSTALLATION-V1'),
  purpose text NOT NULL CHECK (purpose IN ('register','query')),
  nonce text NOT NULL CHECK (nonce ~ '^[A-Za-z0-9_-]{43}$'),
  actor_id text NOT NULL CHECK (char_length(actor_id) BETWEEN 1 AND 80 AND actor_id !~ '[[:cntrl:]]'),
  session_id text NOT NULL CHECK (char_length(session_id) BETWEEN 1 AND 80),
  origin text NOT NULL CHECK (char_length(origin) BETWEEN 1 AND 2048 AND origin ~ '^https?://[^/@?#[:space:]]+$'),
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  public_key_spki text CHECK (public_key_spki ~ '^[A-Za-z0-9_-]{122}$'),
  FOREIGN KEY (session_id,actor_id) REFERENCES auth_sessions(id,user_id),
  CHECK (jsonb_typeof(scope_id::jsonb) = 'array' AND jsonb_array_length(scope_id::jsonb) = 2
    AND jsonb_typeof(scope_id::jsonb->0) = 'string' AND scope_id::jsonb->>0 = namespace_id::text
    AND (scope_id::jsonb->1 = 'null'::jsonb OR (jsonb_typeof(scope_id::jsonb->1) = 'string'
      AND char_length(scope_id::jsonb->>1) BETWEEN 1 AND 80))),
  CHECK (expires_at > created_at AND expires_at <= created_at + interval '60 seconds'),
  CHECK ((purpose = 'register' AND public_key_spki IS NOT NULL) OR (purpose = 'query' AND public_key_spki IS NULL))
);
CREATE INDEX station_installation_challenges_expiry ON station_installation_challenges(expires_at);
CREATE INDEX station_installation_challenges_binding ON station_installation_challenges(scope_id,station_id,installation_id);

CREATE FUNCTION protect_station_installation_scope() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'The station installation namespace is immutable';
END $$;
CREATE TRIGGER immutable_station_installation_scope BEFORE UPDATE OR DELETE ON station_installation_scope
  FOR EACH ROW EXECUTE FUNCTION protect_station_installation_scope();

CREATE FUNCTION protect_station_installation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Station installation registrations cannot be deleted'; END IF;
  IF (to_jsonb(NEW) - ARRAY['status','revision','revoked_at','revoked_by','revocation_reason'])
      IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status','revision','revoked_at','revoked_by','revocation_reason']) THEN
    RAISE EXCEPTION 'Station installation keys and registration history are immutable';
  END IF;
  IF to_jsonb(NEW) IS DISTINCT FROM to_jsonb(OLD) AND
      (OLD.status <> 'active' OR NEW.status <> 'revoked' OR NEW.revision = OLD.revision) THEN
    RAISE EXCEPTION 'Station installations only allow an irreversible revocation';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER immutable_station_installation BEFORE UPDATE OR DELETE ON station_installations
  FOR EACH ROW EXECUTE FUNCTION protect_station_installation();

CREATE FUNCTION protect_station_installation_challenge() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Station installation challenges cannot be changed';
END $$;
CREATE TRIGGER immutable_station_installation_challenge BEFORE UPDATE ON station_installation_challenges
  FOR EACH ROW EXECUTE FUNCTION protect_station_installation_challenge();
